#!/usr/bin/env python3
"""Build platform-specific install packs for AgentCounsel.

Generates dist/ with consolidated and zipped skill packs for ChatGPT
Projects, Claude Projects, Gemini Notebooks, and repo-agent environments.
Every pack is generated from the canonical skills/ and core/ directories;
nothing is duplicated by hand. Standard library only — no dependencies.

    python scripts/build_platform_packs.py

The build fails (exit code 1) if a skill is missing a required section, a
generated pack is empty, a practice area has no index entry, or required
safety language is missing from a pack. See README.md.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
CORE_DIR = REPO_ROOT / "core"
PROFILES_DIR = REPO_ROOT / "practice-profiles"
COMMANDS_FILE = REPO_ROOT / "COMMANDS.md"
DIST = REPO_ROOT / "dist"
PACKS_METADATA = REPO_ROOT / "metadata" / "packs.json"
PACK_SCHEMA_VERSION = "1.0"
PACK_SOURCE_DATE = "2026-05-28"

REQUIRED_SECTIONS = [
    "Purpose", "Use When", "Required Inputs", "Do Not Use When",
    "Legal Safety Rules", "Workflow", "Output Format",
    "Attorney Verification Checklist",
]

# core/ files, split into the always-on rules and the review checklist.
CORE_SAFETY_FILES = [
    "legal-work-product.md",
    "source-and-citation-discipline.md",
    "jurisdiction-and-deadline-gates.md",
    "confidentiality-and-privilege.md",
    "output-format-rules.md",
]
CORE_CHECKLIST_FILE = "attorney-review-checklist.md"
CORE_ALL = CORE_SAFETY_FILES + [CORE_CHECKLIST_FILE]
QUALITY_CHECK_FILES = {
    "assumption-audit": "skills/legal-methodology/assumption-audit/SKILL.md",
    "attorney-review-gate": "skills/legal-methodology/attorney-review-gate/SKILL.md",
    "citation-integrity-check": "skills/legal-methodology/citation-integrity-check/SKILL.md",
    "hallucination-red-team": "skills/legal-methodology/hallucination-red-team/SKILL.md",
    "legal-prose-polish": "skills/legal-methodology/legal-prose-polish/SKILL.md",
    "output-format-compliance-check": "skills/legal-methodology/output-format-compliance-check/SKILL.md",
    "privilege-confidentiality-check": "skills/legal-methodology/privilege-confidentiality-check/SKILL.md",
    "source-validation-check": "skills/legal-methodology/source-validation/SKILL.md",
    "jurisdiction-deadline-gates": "core/jurisdiction-and-deadline-gates.md",
}

# Every generated pack must carry the AgentCounsel safety framing.
REQUIRED_SAFETY_PHRASES = ["draft legal work product", "attorney review"]

# Canonical multi-file matter workspace template assets. Packs whose workflow
# type justifies a workspace (they reference a matter pack, matter workspace,
# playbook, or review panel) also carry the source/citation and attorney-review
# templates so the quality layer has something to attach to.
WORKSPACE_TEMPLATE_DIR = "matter-workspaces/_template"
WORKSPACE_SOURCE_CITATION_TEMPLATES = [
    "matter-workspaces/_template/source_log.md",
    "matter-workspaces/_template/citation_map.md",
    "matter-workspaces/_template/unsupported_claims.md",
    "matter-workspaces/_template/assumptions.md",
]
WORKSPACE_ATTORNEY_REVIEW_TEMPLATES = [
    "matter-workspaces/_template/attorney_review.md",
]

AREA_NAMES = {
    "legal-research": "Legal Research",
    "litigation": "Litigation",
    "contracts": "Contracts",
    "corporate": "Corporate",
    "employment": "Employment",
    "privacy": "Privacy",
    "product-legal": "Product Legal",
    "regulatory": "Regulatory",
    "ai-governance": "AI Governance",
    "insurance": "Insurance",
    "ip": "Intellectual Property",
    "legal-methodology": "Legal Methodology",
    "setup": "Setup",
}
AREA_ORDER = list(AREA_NAMES.keys())

ZIP_DATE = (2026, 1, 1, 0, 0, 0)
GEN_NOTICE = ("> Generated by `scripts/build_platform_packs.py` from the "
              "canonical `skills/` and `core/` directories. Do not edit by "
              "hand — re-run the build to refresh it.\n")

errors: list[str] = []
written: list[Path] = []


def err(msg: str) -> None:
    errors.append(msg)


def area_name(area: str) -> str:
    return AREA_NAMES.get(area, area.replace("-", " ").title())


# --- parsing ---------------------------------------------------------------

def parse_frontmatter(text: str):
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return "", text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join(lines[1:i]), "\n".join(lines[i + 1:])
    return "", text


def parse_skill(md_path: Path) -> dict:
    raw = md_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    name = ""
    description = ""
    nm = re.search(r"^name:\s*(.+)$", fm, re.M)
    if nm:
        name = nm.group(1).strip()
    dm = re.search(r"^description:\s*(.+)$", fm, re.M)
    if dm:
        description = dm.group(1).strip()
    h1 = re.search(r"^#\s+(.+)$", body, re.M)
    if not name and h1:
        name = h1.group(1).strip()
    section_names = [m.group(1).strip()
                     for m in re.finditer(r"^##\s+(.+)$", body, re.M)]
    return {
        "name": name, "description": description, "raw": raw, "body": body,
        "section_names": section_names,
    }


CMD_ROW = re.compile(
    r"^\|\s*`(/[^`]+)`\s*\|\s*`(skills/[^`]+?/SKILL\.md)`\s*\|(.+)\|\s*$")


def load_commands() -> dict:
    commands: dict[str, dict] = {}
    if not COMMANDS_FILE.is_file():
        return commands
    for line in COMMANDS_FILE.read_text(encoding="utf-8").split("\n"):
        m = CMD_ROW.match(line.strip())
        if not m:
            continue
        cells = [c.strip() for c in m.group(3).split("|")]
        commands[m.group(2)] = {
            "command": m.group(1),
            "triggers": cells[0] if len(cells) > 0 else "",
            "inputs": cells[1] if len(cells) > 1 else "",
            "output": cells[2] if len(cells) > 2 else "",
        }
    return commands


def load_areas() -> dict:
    areas: dict[str, dict] = {}
    for area_dir in sorted(p for p in SKILLS_DIR.iterdir() if p.is_dir()):
        area = area_dir.name
        skills = []
        for sd in sorted(p for p in area_dir.iterdir() if p.is_dir()):
            if sd.name == "references":
                continue
            md = sd / "SKILL.md"
            if not md.is_file():
                continue
            sk = parse_skill(md)
            sk["slug"] = sd.name
            sk["area"] = area
            sk["path"] = f"skills/{area}/{sd.name}/SKILL.md"
            for required in REQUIRED_SECTIONS:
                if required not in sk["section_names"]:
                    err(f"skill {sk['path']} is missing required section "
                        f"'## {required}'")
            templates = []
            tdir = sd / "templates"
            if tdir.is_dir():
                for f in sorted(tdir.iterdir()):
                    if f.is_file():
                        templates.append((f.name, f.read_text(encoding="utf-8")))
            sk["templates"] = templates
            skills.append(sk)
        references = []
        rdir = area_dir / "references"
        if rdir.is_dir():
            for f in sorted(rdir.iterdir()):
                if f.is_file() and f.suffix == ".md":
                    references.append((f.name, f.read_text(encoding="utf-8")))
        if skills:
            areas[area] = {"skills": skills, "references": references}
    return areas


def load_skill_metadata_by_path() -> dict:
    try:
        import build_skill_index
    except Exception as exc:
        print(f"warning: could not import build_skill_index for metadata "
              f"enrichment ({exc}); proceeding without enrichment", file=sys.stderr)
        return {}
    return {s["path"]: s for s in build_skill_index.build_index()["skills"]}


def area_template_paths(area_info: dict) -> list[str]:
    paths: list[str] = []
    for sk in area_info["skills"]:
        for tname, _ in sk["templates"]:
            paths.append(
                f"skills/{sk['area']}/{sk['slug']}/templates/{tname}")
    for rname, _ in area_info["references"]:
        paths.append(f"skills/{area_info['skills'][0]['area']}/references/{rname}")
    return sorted(paths)


def markdown_title(path: Path) -> str:
    if not path.is_file():
        return path.stem.replace("-", " ").title()
    m = re.search(r"^#\s+(.+)$", path.read_text(encoding="utf-8"), re.M)
    return m.group(1).strip() if m else path.stem.replace("-", " ").title()


def files_referencing_area(base: Path, area: str) -> list[str]:
    found: list[str] = []
    if not base.is_dir():
        return found
    pattern = f"skills/{area}/"
    for path in sorted(base.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        if pattern in text:
            found.append(path.relative_to(REPO_ROOT).as_posix())
    return found


def quality_checks_for_skills(skills: list, skill_meta: dict) -> list[str]:
    checks: list[str] = []
    for sk in skills:
        record = skill_meta.get(sk["path"], {})
        for q in record.get("recommended_quality_checks", []):
            if q not in checks:
                checks.append(q)
    return checks


def build_pack_registry(areas: dict) -> dict:
    skill_meta = load_skill_metadata_by_path()
    order = ordered_areas(areas)
    packs: list[dict] = []
    core_rules = [f"core/{name}" for name in CORE_ALL]
    safety = (
        "Every AgentCounsel pack produces draft legal work product for review "
        "by a licensed attorney. It is not legal advice, and it does not "
        "replace attorney verification."
    )

    for area in order:
        info = areas[area]
        skills = [s["path"] for s in info["skills"]]
        templates = area_template_paths(info)
        matter_packs = files_referencing_area(REPO_ROOT / "matter-packs", area)
        workspaces = files_referencing_area(REPO_ROOT / "matter-workspaces", area)
        playbooks = files_referencing_area(REPO_ROOT / "playbooks", area)
        review_panels = files_referencing_area(REPO_ROOT / "review-panels", area)
        quality_checks = quality_checks_for_skills(info["skills"], skill_meta)
        # Only carry workspace tooling where the workflow type justifies it.
        workspace_justified = bool(
            matter_packs or workspaces or playbooks or review_panels
        )
        source_citation_templates = (
            list(WORKSPACE_SOURCE_CITATION_TEMPLATES) if workspace_justified else []
        )
        attorney_review_templates = (
            list(WORKSPACE_ATTORNEY_REVIEW_TEMPLATES) if workspace_justified else []
        )
        common = {
            "practice_area": area,
            "practice_area_name": area_name(area),
            "use_case": "practice-area legal workflow pack",
            "included_skills": skills,
            "included_core_rules": core_rules,
            "included_templates": templates,
            "included_quality_checks": quality_checks,
            "included_matter_packs": matter_packs,
            "included_matter_workspace_templates": workspaces,
            "included_playbooks": playbooks,
            "included_review_panels": review_panels,
            "included_source_citation_templates": source_citation_templates,
            "included_attorney_review_templates": attorney_review_templates,
            "safety_disclaimer": safety,
            "attorney_review_requirements": [
                "A licensed attorney must review and adopt all outputs before reliance.",
                "The agent must not invent legal authority, citations, quotations, facts, or deadlines.",
                "Jurisdiction, governing law, posture, and deadlines must be supplied or flagged as unknown.",
            ],
            "version": PACK_SCHEMA_VERSION,
            "date": PACK_SOURCE_DATE,
        }
        pack_defs = [
            ("chatgpt", f"chatgpt/{area}.md",
             "Upload the Markdown pack to a ChatGPT Project and add the generated project instructions."),
            ("claude", f"claude/{area}.zip",
             "Unzip into Claude Project knowledge or a plugin-style workspace and follow CLAUDE.md."),
            ("gemini", f"gemini/{area}.zip",
             "Add the notebook source files to Gemini and follow notebook-instructions.md."),
        ]
        for platform, output, setup in pack_defs:
            packs.append({
                "pack_id": f"{platform}/{area}",
                "platform": platform,
                "output": output,
                "setup_instructions": setup,
                **common,
            })

    packs.append({
        "pack_id": "repo-agents/global",
        "platform": "codex-cursor-claude-code",
        "practice_area": "all",
        "practice_area_name": "All Practice Areas",
        "use_case": "repo-agent instruction files",
        "output": "repo-agents/",
        "included_skills": [],
        "included_core_rules": core_rules,
        "included_templates": [],
        "included_quality_checks": sorted(QUALITY_CHECK_FILES),
        "included_matter_packs": [],
        "included_matter_workspace_templates": [],
        "included_playbooks": [],
        "included_review_panels": [],
        "included_source_citation_templates": [],
        "included_attorney_review_templates": [],
        "setup_instructions": "Copy the generated AGENTS.md, CLAUDE.md, or .cursorrules file into a repository root.",
        "safety_disclaimer": safety,
        "attorney_review_requirements": [
            "Repo agents must route to the narrowest relevant skill.",
            "All legal outputs remain draft work product for attorney review.",
        ],
        "version": PACK_SCHEMA_VERSION,
        "date": PACK_SOURCE_DATE,
    })

    return {
        "generated_by": "scripts/build_platform_packs.py",
        "schema_version": PACK_SCHEMA_VERSION,
        "date": PACK_SOURCE_DATE,
        "platforms": ["chatgpt", "claude", "gemini", "cursor", "codex"],
        "quality_checks": [
            {"id": key, "path": value}
            for key, value in sorted(QUALITY_CHECK_FILES.items())
        ],
        "packs": packs,
    }


def render_pack_registry(areas: dict) -> str:
    return json.dumps(build_pack_registry(areas), indent=2) + "\n"


def validate_pack_registry(registry: dict, check_outputs: bool = False) -> list[str]:
    problems: list[str] = []
    valid_checks = set(QUALITY_CHECK_FILES)
    for check_id, path in QUALITY_CHECK_FILES.items():
        if not (REPO_ROOT / path).exists():
            problems.append(f"quality check '{check_id}' target missing: {path}")
    for pack in registry.get("packs", []):
        pid = pack.get("pack_id", "<missing>")
        for field in (
            "pack_id", "platform", "practice_area", "included_skills",
            "included_core_rules", "included_quality_checks",
            "setup_instructions", "safety_disclaimer",
            "attorney_review_requirements", "version", "date",
        ):
            if field not in pack:
                problems.append(f"{pid}: missing manifest field '{field}'")
        for path in pack.get("included_skills", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: skill path missing: {path}")
        for path in pack.get("included_core_rules", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: core rule missing: {path}")
        for path in pack.get("included_templates", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: template/reference missing: {path}")
        for path in pack.get("included_matter_packs", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: matter pack missing: {path}")
        for path in pack.get("included_matter_workspace_templates", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: matter workspace missing: {path}")
        for path in pack.get("included_playbooks", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: playbook missing: {path}")
        for path in pack.get("included_review_panels", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: review panel missing: {path}")
        for path in pack.get("included_source_citation_templates", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: source/citation template missing: {path}")
        for path in pack.get("included_attorney_review_templates", []):
            if not (REPO_ROOT / path).is_file():
                problems.append(f"{pid}: attorney-review template missing: {path}")
        for check_id in pack.get("included_quality_checks", []):
            if check_id not in valid_checks:
                problems.append(f"{pid}: unknown quality check: {check_id}")
        if "draft legal work product" not in pack.get("safety_disclaimer", "").lower():
            problems.append(f"{pid}: safety disclaimer missing draft-work-product posture")
        if check_outputs:
            output = pack.get("output", "")
            if output.endswith("/"):
                if not (DIST / output).is_dir():
                    problems.append(f"{pid}: generated output folder missing: {output}")
            elif output and not (DIST / output).is_file():
                problems.append(f"{pid}: generated output file missing: {output}")
    return problems


def ordered_areas(areas: dict) -> list[str]:
    known = [a for a in AREA_ORDER if a in areas]
    return known + sorted(a for a in areas if a not in AREA_ORDER)


# --- markdown helpers ------------------------------------------------------

def demote(md: str, levels: int) -> str:
    if levels <= 0:
        return md
    out, fence = [], False
    for line in md.split("\n"):
        if line.lstrip().startswith("```"):
            fence = not fence
            out.append(line)
            continue
        if not fence:
            m = re.match(r"^(#{1,6})(\s)", line)
            if m:
                lvl = min(len(m.group(1)) + levels, 6)
                out.append("#" * lvl + line[len(m.group(1)):])
                continue
        out.append(line)
    return "\n".join(out)


def strip_first_h1(body: str) -> str:
    out, removed = [], False
    for line in body.split("\n"):
        if not removed and re.match(r"^#\s+\S", line):
            removed = True
            continue
        out.append(line)
    return "\n".join(out).strip()


def skill_block(sk: dict, base_level: int) -> str:
    """Render a skill under a heading of base_level, with its sections one
    level deeper."""
    head = "#" * base_level
    body = demote(strip_first_h1(sk["body"]), base_level - 1)
    return (f"{head} {sk['name']}\n\n"
            f"*Agent trigger:* {sk['description']}\n\n"
            f"*Canonical path:* `{sk['path']}`\n\n"
            f"{body}\n")


def profile_text(area: str) -> str:
    pf = PROFILES_DIR / f"{area}.md"
    if pf.is_file():
        return pf.read_text(encoding="utf-8")
    return (f"The {area_name(area)} practice area does not ship a standalone "
            f"practice profile. Configure agent behavior using the global "
            f"safety rules and your team's own conventions. See "
            f"`practice-profiles/README.md` in the AgentCounsel repository.\n")


def commands_table(skills: list, commands: dict) -> str:
    rows = ["| Command | Skill | Trigger phrases | Required inputs |"
            " Expected output |",
            "|---|---|---|---|---|"]
    for sk in skills:
        c = commands.get(sk["path"])
        if c:
            rows.append(f"| `{c['command']}` | {sk['name']} | {c['triggers']} "
                        f"| {c['inputs']} | {c['output']} |")
        else:
            rows.append(f"| _(no command)_ | {sk['name']} | "
                        f"{sk['description']} | | |")
    return "\n".join(rows) + "\n"


def usage_examples(area: str, skills: list) -> str:
    parts = ["These examples show one-off use — a single prompt pasted into "
             "any AI assistant, with no project setup. The skill text comes "
             "from the Skills section of this pack.\n"]
    for sk in skills[:2]:
        parts.append(f"**Using \"{sk['name']}\"**\n")
        parts.append(
            f"> Use the AgentCounsel \"{sk['name']}\" skill from this pack. "
            f"Follow its Workflow and Output Format exactly. Produce draft "
            f"legal work product for attorney review — this is not legal "
            f"advice. Do not invent legal authority, citations, quotations, "
            f"or deadlines; flag every gap with a placeholder such as "
            f"`[CONFIRM: ...]`. Then complete the skill's Attorney "
            f"Verification Checklist.\n>\n"
            f"> Paste the \"{sk['name']}\" skill section here, then provide "
            f"its Required Inputs. If an input is missing, stop and ask.\n")
    return "\n".join(parts)


# --- pack content ----------------------------------------------------------

def chatgpt_instructions(nm: str) -> str:
    return (
        f"1. In ChatGPT, create a new Project for your {nm} work.\n"
        f"2. Upload this file to the Project's files. Because ChatGPT Projects "
        f"limit the number of files, this pack consolidates the whole "
        f"{nm} practice area into one file.\n"
        f"3. In the Project instructions, tell ChatGPT: \"Follow the "
        f"AgentCounsel pack in the Project files. Apply the global safety "
        f"rules to every task. Use the practice profile and the skill that "
        f"matches the request. Produce draft legal work product for attorney "
        f"review — not legal advice.\"\n"
        f"4. Start a chat, name the task, and let ChatGPT route to the right "
        f"skill below.\n"
        f"5. Provide the skill's Required Inputs, follow its Workflow, and "
        f"complete its Attorney Verification Checklist before relying on "
        f"anything.\n")


def chatgpt_pack(area: str, info: dict, commands: dict) -> str:
    nm = area_name(area)
    skills = info["skills"]
    p = [f"# AgentCounsel — {nm} Pack (ChatGPT Projects)\n", GEN_NOTICE,
         f"This pack consolidates the AgentCounsel **{nm}** practice area for "
         f"a ChatGPT Project: platform instructions, the global safety rules, "
         f"the practice profile, the command list, every skill, the attorney "
         f"review checklist, and one-off usage examples — in a single file. "
         f"Every output produced with it is draft legal work product for "
         f"review by a licensed attorney; it is not legal advice.\n",
         "## 1. How to use this pack in a ChatGPT Project\n",
         chatgpt_instructions(nm),
         "## 2. Global safety rules\n",
         "These operating rules apply to every skill in this pack.\n"]
    for fname in CORE_SAFETY_FILES:
        p.append(demote((CORE_DIR / fname).read_text(encoding="utf-8"), 2))
    p.append("## 3. Practice profile\n")
    p.append("The practice profile records this team's jurisdictions, "
             "escalation thresholds, standard positions, and prohibited "
             "assumptions. Complete every placeholder before relying on it.\n")
    p.append(demote(profile_text(area), 2))
    p.append(f"## 4. Commands for {nm}\n")
    p.append("Slash-style shorthands for the skills in this pack.\n")
    p.append(commands_table(skills, commands))
    p.append("## 5. Skills\n")
    p.append(f"All {len(skills)} skills in the {nm} practice area. Each "
             f"produces draft legal work product for attorney review.\n")
    for sk in skills:
        p.append(skill_block(sk, 3))
    p.append("## 6. Attorney review checklist\n")
    p.append(demote((CORE_DIR / CORE_CHECKLIST_FILE).read_text(encoding="utf-8"),
                    2))
    p.append("## 7. One-off usage examples\n")
    p.append(usage_examples(area, skills))
    return "\n".join(p) + "\n"


def chatgpt_project_instructions(areas: dict) -> str:
    rows = []
    for area in ordered_areas(areas):
        rows.append(f"- **{area_name(area)}** — `chatgpt/{area}.md` "
                    f"({len(areas[area]['skills'])} skills)")
    return (
        "# AgentCounsel — ChatGPT Projects: Global Instructions\n\n"
        + GEN_NOTICE +
        "\nAgentCounsel is an open, platform-agnostic legal skills library. "
        "Each skill is a structured workflow that produces **draft legal work "
        "product for review by a licensed attorney** — never legal advice and "
        "never a final answer.\n\n"
        "## Setting up\n\n"
        "1. Create one ChatGPT Project per practice area you work in.\n"
        "2. Upload that practice area's consolidated pack file (listed below) "
        "to the Project.\n"
        "3. Paste the operating instruction into the Project's custom "
        "instructions: \"Follow the AgentCounsel pack in the Project files. "
        "Apply its global safety rules to every task, use the practice "
        "profile, and follow the skill that matches the request. Produce "
        "draft legal work product for attorney review — not legal advice. "
        "Never invent authority, citations, or deadlines.\"\n"
        "4. Start a chat and describe the task.\n\n"
        "## Practice-area packs\n\n"
        + "\n".join(rows) + "\n\n"
        "## The safety model\n\n"
        "Every pack carries the AgentCounsel core rules. Output is draft work "
        "product only; a licensed legal professional must review and adopt it "
        "before it is relied upon. The agent must never invent legal "
        "authority, citations, quotations, facts, or deadlines, and must flag "
        "gaps with placeholders rather than guessing.\n")


def claude_md(nm: str) -> str:
    return (
        f"# AgentCounsel — {nm} (Claude Project)\n\n"
        + GEN_NOTICE +
        f"\nThis Claude Project contains the AgentCounsel **{nm}** practice "
        f"area. Treat the files in Project knowledge as a reference library.\n\n"
        "## How to work\n\n"
        "1. The core operating rules are embedded in every skill's context "
        "and summarized here: produce **draft legal work product for review "
        "by a licensed attorney**, never legal advice; never invent legal "
        "authority, citations, quotations, facts, or deadlines; identify "
        "jurisdiction, governing law, posture, and the relevant date, or flag "
        "them; preserve confidentiality and privilege; flag gaps with "
        "placeholders such as `[CONFIRM: ...]`.\n"
        "2. Use `commands.md` and the skill files in `skills/` to pick the "
        "narrowest skill for the task.\n"
        "3. Read that skill's `SKILL.md` and any matching file in "
        "`templates/`.\n"
        "4. Follow the skill's Workflow and Output Format.\n"
        "5. Complete the skill's Attorney Verification Checklist before the "
        "work product is relied upon.\n\n"
        "## Practice profile\n\n"
        "`practice-profile-template.md` configures agent behavior for this "
        "team. Complete its placeholders and have a supervising attorney "
        "approve it before relying on it.\n\n"
        "Every output is draft legal work product for attorney review. It is "
        "not legal advice.\n")


def claude_readme(nm: str, skills: list) -> str:
    lines = [f"# AgentCounsel — {nm} Claude Project Pack\n", GEN_NOTICE,
             f"\nInstall pack for using the AgentCounsel **{nm}** practice "
             f"area in a Claude Project.\n",
             "## Contents\n",
             "- `CLAUDE.md` — operating instructions for the project.",
             "- `practice-profile-template.md` — the team configuration "
             "profile.",
             "- `commands.md` — slash-style commands for this practice area.",
             "- `skills/` — one `SKILL.md` per skill.",
             "- `templates/` — copyable, attorney-review-ready templates.",
             "- `README.md` — this file.\n",
             "## Install\n",
             "1. Create a new Project in Claude.",
             "2. Add every file in this archive to the Project knowledge, "
             "keeping the folder structure.",
             "3. Paste the guidance from `CLAUDE.md` into the Project "
             "instructions.",
             "4. Start a conversation and name your task.\n",
             "## Skills in this pack\n"]
    for sk in skills:
        lines.append(f"- **{sk['name']}** — {sk['description']}")
    lines.append("\nEvery output is draft legal work product for attorney "
                 "review. It is not legal advice.\n")
    return "\n".join(lines)


def commands_doc(nm: str, skills: list, commands: dict) -> str:
    return (f"# AgentCounsel — {nm} Commands\n\n" + GEN_NOTICE +
            f"\nSlash-style command shorthands for the {nm} skills in this "
            f"pack. Each command points to a skill; run the skill it names.\n\n"
            + commands_table(skills, commands))


def gemini_notebook_instructions(nm: str) -> str:
    return (
        f"# AgentCounsel — {nm} (Gemini Notebook)\n\n"
        + GEN_NOTICE +
        f"\nThis pack adapts the AgentCounsel **{nm}** practice area for a "
        f"Gemini notebook. The four `source-*.md` files are designed to be "
        f"added as notebook sources.\n\n"
        "## Install\n\n"
        "1. Create a notebook in your Gemini environment.\n"
        "2. Add these files as sources, in order:\n"
        "   - `source-1-core-rules.md` — the operating and safety rules.\n"
        "   - `source-2-practice-profile.md` — the team configuration "
        "profile.\n"
        "   - `source-3-skills.md` — every skill in the practice area.\n"
        "   - `source-4-templates.md` — copyable templates and references.\n"
        "3. Ask Gemini to follow the skill that matches your task, applying "
        "the core rules and the practice profile.\n\n"
        "## The rule\n\n"
        "Every output is **draft legal work product for review by a licensed "
        "attorney** — not legal advice. The agent must never invent legal "
        "authority, citations, quotations, facts, or deadlines, and must flag "
        "gaps with placeholders. Complete each skill's Attorney Verification "
        "Checklist before relying on the work.\n")


def gemini_core_source() -> str:
    p = ["# AgentCounsel — Core Rules (Source 1)\n", GEN_NOTICE,
         "\nThe operating rules every AgentCounsel skill inherits. They always "
         "apply: produce draft legal work product for attorney review, never "
         "legal advice.\n"]
    for fname in CORE_ALL:
        p.append(demote((CORE_DIR / fname).read_text(encoding="utf-8"), 1))
    return "\n".join(p) + "\n"


def gemini_skills_source(nm: str, skills: list) -> str:
    p = [f"# AgentCounsel — {nm} Skills (Source 3)\n", GEN_NOTICE,
         f"\nAll {len(skills)} skills in the {nm} practice area. Each is a "
         f"workflow that produces draft legal work product for attorney "
         f"review.\n"]
    for sk in skills:
        p.append(skill_block(sk, 2))
    return "\n".join(p) + "\n"


def gemini_templates_source(nm: str, info: dict) -> str:
    p = [f"# AgentCounsel — {nm} Templates (Source 4)\n", GEN_NOTICE]
    items = []
    for sk in info["skills"]:
        for tname, tcontent in sk["templates"]:
            items.append((f"{sk['name']} — {tname}", tcontent))
    for rname, rcontent in info["references"]:
        items.append((f"Reference — {rname}", rcontent))
    if not items:
        p.append("\nThe skills in this practice area do not ship templates "
                 "or reference files.\n")
        return "\n".join(p) + "\n"
    p.append(f"\nCopyable, attorney-review-ready templates and reference "
             f"material for the {nm} skills.\n")
    for title, content in items:
        p.append(f"## {title}\n")
        p.append(demote(content, 2))
    return "\n".join(p) + "\n"


def repo_agent_files() -> dict:
    shared_rules = (
        "- Read the six files in `core/` first — they apply to every skill.\n"
        "- Route the task with `WORKFLOW_ROUTER.md` or `COMMANDS.md`; browse "
        "with `SKILLS_INDEX.md`.\n"
        "- Select the single narrowest relevant skill in `skills/` and read "
        "its `SKILL.md` and any `templates/`.\n"
        "- Follow the skill's Workflow and Output Format. Complete its "
        "Attorney Verification Checklist.\n"
        "- Produce **draft legal work product for review by a licensed "
        "attorney** — never legal advice, never a final answer.\n"
        "- Never invent legal authority, citations, quotations, facts, or "
        "deadlines. Flag gaps with placeholders such as `[CONFIRM: ...]`.\n"
        "- Identify jurisdiction, governing law, posture, and the relevant "
        "date, or flag them as unknown. Preserve confidentiality and "
        "privilege.\n"
        "- If no skill fits, say so. Do not improvise a legal workflow.\n")

    agents = (
        "# AGENTS.md — AgentCounsel\n\n" + GEN_NOTICE +
        "\nThis repository uses **AgentCounsel**, a Markdown-native legal "
        "skills library. If you are a Codex or other repo-based agent, follow "
        "these instructions.\n\n"
        "## Canonical library\n\n"
        "The skill library is `skills/`; the operating rules are `core/`. "
        "Treat them as the source of truth. `CONTEXT.md` defines the "
        "repository's vocabulary.\n\n"
        "## How to work\n\n" + shared_rules)

    claude = (
        "# CLAUDE.md — AgentCounsel\n\n" + GEN_NOTICE +
        "\nThis repository uses **AgentCounsel**, a Markdown-native legal "
        "skills library. When working here with Claude Code, treat `skills/` "
        "and `core/` as a read-only reference library unless the task is "
        "explicitly to improve the library itself.\n\n"
        "## How to work\n\n" + shared_rules +
        "\nDo not modify skill files while using them; deliver work product "
        "as separate documents.\n")

    cursor = (
        "AgentCounsel — Cursor project rules\n"
        "Generated by scripts/build_platform_packs.py. Re-run the build to "
        "refresh.\n\n"
        "This repository uses AgentCounsel, a Markdown-native legal skills "
        "library. When asked for legal drafting or review work:\n\n"
        + shared_rules.replace("`", "") +
        "\nThe canonical library is the skills/ and core/ directories. Output "
        "is draft legal work product for attorney review, not legal advice.\n")

    readme = (
        "# AgentCounsel — Repo-Agent Install Pack\n\n" + GEN_NOTICE +
        "\nInstall files for using AgentCounsel from a repo-based coding or "
        "legal agent. Each file tells one agent environment how to use the "
        "canonical `skills/` and `core/` library in a checkout of the "
        "AgentCounsel repository.\n\n"
        "## Files\n\n"
        "- `AGENTS.md` — for Codex and other agents that read `AGENTS.md`. "
        "Place it at the repository root.\n"
        "- `CLAUDE.md` — for Claude Code. Place it at the repository root.\n"
        "- `.cursorrules` — for Cursor. Place it at the repository root.\n"
        "- `README.md` — this generic install guide.\n\n"
        "## Install\n\n"
        "1. Copy the file for your agent environment into the root of your "
        "AgentCounsel checkout (or the repository that vendors `skills/` and "
        "`core/`).\n"
        "2. Start your agent. It will read the instruction file and route "
        "tasks to the canonical skills.\n\n"
        "Every output is draft legal work product for attorney review. It is "
        "not legal advice.\n")

    return {
        "AGENTS.md": agents,
        "CLAUDE.md": claude,
        ".cursorrules": cursor,
        "README.md": readme,
    }


# --- writing ---------------------------------------------------------------

def write_text(rel: str, content: str) -> None:
    path = DIST / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    written.append(path)


def write_zip(rel: str, members: list) -> None:
    path = DIST / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        for arcname, content in members:
            info = zipfile.ZipInfo(arcname, date_time=ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, content)
    written.append(path)


def check_safety(label: str, text: str) -> None:
    low = text.lower()
    for phrase in REQUIRED_SAFETY_PHRASES:
        if phrase.lower() not in low:
            err(f"{label}: required safety language missing ('{phrase}')")


def check_not_empty(label: str, members: list) -> None:
    total = sum(len(c) for _, c in members)
    if len(members) < 2 or total < 1000:
        err(f"{label}: generated pack looks empty "
            f"({len(members)} files, {total} bytes)")


# --- main ------------------------------------------------------------------

def run_check() -> int:
    if not SKILLS_DIR.is_dir():
        print("skills/ directory not found", file=sys.stderr)
        return 1
    areas = load_areas()
    expected = render_pack_registry(areas)
    if not PACKS_METADATA.is_file():
        print(f"MISSING: {PACKS_METADATA.relative_to(REPO_ROOT).as_posix()} "
              "has not been generated.")
        print("Run 'python scripts/build_platform_packs.py'.")
        return 1
    if PACKS_METADATA.read_text(encoding="utf-8") != expected:
        print(f"STALE: {PACKS_METADATA.relative_to(REPO_ROOT).as_posix()} "
              "is out of date.")
        print("Run 'python scripts/build_platform_packs.py'.")
        return 1
    problems = validate_pack_registry(build_pack_registry(areas))
    if problems:
        print("Pack manifest validation failed:")
        for problem in problems:
            print(f"  x {problem}")
        return 1
    print(f"{PACKS_METADATA.relative_to(REPO_ROOT).as_posix()} is up to date "
          f"({len(areas)} practice areas).")
    return 0


def run_write() -> int:
    if not SKILLS_DIR.is_dir():
        print("skills/ directory not found", file=sys.stderr)
        return 1

    commands = load_commands()
    areas = load_areas()
    if not areas:
        err("no practice areas with skills were found under skills/")

    PACKS_METADATA.parent.mkdir(parents=True, exist_ok=True)
    pack_registry = build_pack_registry(areas)
    PACKS_METADATA.write_text(
        json.dumps(pack_registry, indent=2) + "\n", encoding="utf-8")
    errors.extend(validate_pack_registry(pack_registry))

    shutil.rmtree(DIST, ignore_errors=True)
    DIST.mkdir(parents=True, exist_ok=True)
    write_text("packs.json", json.dumps(pack_registry, indent=2) + "\n")

    order = ordered_areas(areas)
    index_areas = []

    # ChatGPT: one consolidated file per area + a global instructions file.
    write_text("chatgpt/project-instructions.md",
               chatgpt_project_instructions(areas))
    for area in order:
        info = areas[area]
        text = chatgpt_pack(area, info, commands)
        check_safety(f"chatgpt/{area}.md", text)
        if len(text) < 1500:
            err(f"chatgpt/{area}.md: generated pack looks empty "
                f"({len(text)} bytes)")
        write_text(f"chatgpt/{area}.md", text)

    # Claude: one ZIP per area, folder structure preserved.
    for area in order:
        info = areas[area]
        nm = area_name(area)
        skills = info["skills"]
        members = [
            ("CLAUDE.md", claude_md(nm)),
            ("practice-profile-template.md", profile_text(area)),
            ("commands.md", commands_doc(nm, skills, commands)),
            ("README.md", claude_readme(nm, skills)),
        ]
        for sk in skills:
            members.append((f"skills/{sk['slug']}/SKILL.md", sk["raw"]))
            for tname, tcontent in sk["templates"]:
                members.append((f"templates/{sk['slug']}/{tname}", tcontent))
        for rname, rcontent in info["references"]:
            members.append((f"templates/references/{rname}", rcontent))
        if not any(a.startswith("templates/") for a, _ in members):
            members.append(("templates/README.md",
                            "The skills in this practice area do not ship "
                            "templates.\n"))
        check_safety(f"claude/{area}.zip:CLAUDE.md", members[0][1])
        check_not_empty(f"claude/{area}.zip", members)
        write_zip(f"claude/{area}.zip", members)

    # Gemini: one ZIP per area with four notebook sources.
    for area in order:
        info = areas[area]
        nm = area_name(area)
        members = [
            ("notebook-instructions.md", gemini_notebook_instructions(nm)),
            ("source-1-core-rules.md", gemini_core_source()),
            ("source-2-practice-profile.md",
             f"# AgentCounsel — {nm} Practice Profile (Source 2)\n\n"
             + GEN_NOTICE + "\n" + profile_text(area)),
            ("source-3-skills.md", gemini_skills_source(nm, info["skills"])),
            ("source-4-templates.md", gemini_templates_source(nm, info)),
        ]
        check_safety(f"gemini/{area}.zip:source-1-core-rules.md",
                     members[1][1])
        check_not_empty(f"gemini/{area}.zip", members)
        write_zip(f"gemini/{area}.zip", members)

    # Repo agents: instruction files for several agent environments.
    for fname, content in repo_agent_files().items():
        if len(content) < 200:
            err(f"repo-agents/{fname}: generated file looks empty")
        write_text(f"repo-agents/{fname}", content)

    # Index of practice areas and their packs.
    for area in order:
        info = areas[area]
        index_areas.append({
            "id": area,
            "name": area_name(area),
            "skill_count": len(info["skills"]),
            "skills": [{"slug": s["slug"], "name": s["name"],
                        "path": s["path"]} for s in info["skills"]],
            "packs": {
                "chatgpt": f"chatgpt/{area}.md",
                "claude": f"claude/{area}.zip",
                "gemini": f"gemini/{area}.zip",
            },
        })

    # Validation: every practice area must have an index entry.
    indexed = {a["id"] for a in index_areas}
    for area in areas:
        if area not in indexed:
            err(f"practice area '{area}' has no entry in dist/index.json")

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    total_skills = sum(len(i["skills"]) for i in areas.values())

    index = {
        "name": "AgentCounsel platform packs",
        "generated": generated,
        "generator": "scripts/build_platform_packs.py",
        "totals": {
            "practice_areas": len(index_areas),
            "skills": total_skills,
            "packs": len(index_areas) * 3 + 1 + 4,
        },
        "practice_areas": index_areas,
        "global": {
            "chatgpt_project_instructions": "chatgpt/project-instructions.md",
            "repo_agents": [
                "repo-agents/AGENTS.md", "repo-agents/CLAUDE.md",
                "repo-agents/.cursorrules", "repo-agents/README.md",
            ],
        },
    }
    write_text("index.json", json.dumps(index, indent=2) + "\n")
    write_text("SKILL_PACKS_INDEX.md", skill_packs_index(index_areas))

    # Manifest: every generated file with size and hash.
    files = []
    for path in sorted(written):
        data = path.read_bytes()
        files.append({
            "path": path.relative_to(DIST).as_posix(),
            "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
        })
    manifest = {
        "generated": generated,
        "generator": "scripts/build_platform_packs.py",
        "pack_registry": "metadata/packs.json",
        "file_count": len(files),
        "files": files,
    }
    (DIST / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"AgentCounsel platform packs -> {DIST}")
    print(f"  {len(index_areas)} practice areas, {total_skills} skills")
    print(f"  wrote {PACKS_METADATA.relative_to(REPO_ROOT).as_posix()}")
    print(f"  {len(files) + 1} files written "
          f"(chatgpt, claude, gemini, repo-agents, indexes)")

    errors.extend(validate_pack_registry(pack_registry, check_outputs=True))

    if errors:
        print()
        print(f"BUILD FAILED — {len(errors)} validation error(s):")
        for msg in errors:
            print(f"  x {msg}")
        return 1
    print("  all build-validation checks passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build AgentCounsel platform packs and pack manifests.")
    parser.add_argument(
        "--check", action="store_true",
        help="Verify metadata/packs.json is current and valid; do not write "
             "dist/ or metadata files.")
    args = parser.parse_args()
    return run_check() if args.check else run_write()


def skill_packs_index(index_areas: list) -> str:
    lines = [
        "# AgentCounsel — Platform Skill Packs\n",
        GEN_NOTICE,
        "\nPlatform-specific install packs, generated from the canonical "
        "`skills/` and `core/` directories. Every pack produces **draft legal "
        "work product for review by a licensed attorney** — not legal "
        "advice.\n",
        "## Packs by practice area\n",
        "| Practice area | Skills | ChatGPT | Claude | Gemini |",
        "|---|---|---|---|---|",
    ]
    for a in index_areas:
        lines.append(
            f"| {a['name']} | {a['skill_count']} | `{a['packs']['chatgpt']}` "
            f"| `{a['packs']['claude']}` | `{a['packs']['gemini']}` |")
    lines += [
        "\n## Global files\n",
        "- `chatgpt/project-instructions.md` — global ChatGPT Projects guide.",
        "- `repo-agents/AGENTS.md` — Codex / repo-agent instructions.",
        "- `repo-agents/CLAUDE.md` — Claude Code instructions.",
        "- `repo-agents/.cursorrules` — Cursor project rules.",
        "- `repo-agents/README.md` — generic repo-agent install guide.",
        "- `packs.json`, `index.json`, `manifest.json` — machine-readable indexes.\n",
        "## How to install\n",
        "**ChatGPT Projects.** Create a Project per practice area and upload "
        "that area's `chatgpt/<area>.md` file. Use "
        "`chatgpt/project-instructions.md` for the Project instructions.\n",
        "**Claude Projects.** Unzip `claude/<area>.zip` and add its files to "
        "a Claude Project's knowledge, keeping the folder structure. Follow "
        "the included `CLAUDE.md`.\n",
        "**Gemini Notebooks.** Unzip `gemini/<area>.zip` and add the four "
        "`source-*.md` files as notebook sources. Follow "
        "`notebook-instructions.md`.\n",
        "**Repo agents.** Copy the matching file from `repo-agents/` into the "
        "root of your repository checkout.\n",
        "Every pack is generated. To refresh, run "
        "`python scripts/build_platform_packs.py`.\n",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    sys.exit(main())
